steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/test-registry/quickstart-image:tag1 .
  automapSubstitutions: true
images:
- '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/test-registry/quickstart-image:tag1'